### ISSUE TITLE
Im unable to host my own api instance

### ISSUE THREAD

**Issue by inthelovedotorg** [rajput-hemant/jiosaavn-api-ts#66]
I'm actually using vercel, and tried to host my own api but I couldn't, i somehow when host it on vercel, see an error 404 not found by vercel and the api doesn't works either, can you please provide some assistance

**Comment by rajput-hemant** [comment]
Hey, could you please share the issue or error you're encountering?
Currently, the Bun runtime is set as the default for the repo, but you might be facing an error saying `invalid runtime`.
Try deploying it using the Node runtime. For more info, check out this [link](https://github.com/rajput-hemant/jiosaavn-api-ts?tab=readme-ov-file#vercel)

**Comment by inthelovedotorg** [comment]
I actually directly hosted the api by clicking on the deploy button in the read me file of the repository, and vercel didn't really asked for any env configurations aswell and deployed the  repository but when it did I saw error saying 404 not found when I went to the url, I also tried using postman to check the api but the error was same as 404 not found

**Comment by inthelovedotorg** [comment]
I actually directly hosted the api by clicking on the deploy button in the read me file of the repository, and vercel didn't really asked for any env configurations aswell and deployed the  repository but when it did I saw error saying 404 not found when I went to the url, I also tried using postman to check the api but the error was same as 404 not found, ill try running on node runtime as you said and see if it works

**Comment by inthelovedotorg** [comment]
yup tysm it worked.

**Comment by rajput-hemant** [comment]
great 👍🏻
