### ISSUE TITLE
Cannot deploy a new instance

### ISSUE THREAD

**Issue by Razamindset** [rajput-hemant/jiosaavn-api-ts#75]
I followed simple deployment steps and i get this error

`Build Failed
The following Serverless Functions contain an invalid "runtime": - App (provided.al2)`

I have no idea what this is....:)

**Comment by rajput-hemant** [comment]
@Razamindset https://github.com/rajput-hemant/jiosaavn-api-ts/issues/66#issuecomment-2385249340
